import type { AccessoryCategory } from "@/lib/accessory-types";

function item(
  id: string,
  name: string,
  options: string,
  numberChange: "need" | "max" | "na",
  obtain: string,
  recommended: boolean,
) {
  return { id, name, icon: "", options, numberChange, obtain, recommended };
}

export const ACCESSORY_SEEDS: AccessoryCategory[] = [
  {
    slug: "rings",
    title: "Rings",
    blurb:
      "Ring options roll Attack, Skill, Attribute, Critical, HP, DS, and Defense. Number Change Stone is required on sealed pieces that do not already roll max numbers.",
    roles: [
      { role: "SK", primary: "Attack, Skill", secondary: "Attribute, Max HP" },
      { role: "AA", primary: "Attack, Critical", secondary: "Attribute, Max HP" },
      { role: "TA", primary: "Max HP, Defense", secondary: "Attack" },
      { role: "SUP", primary: "Max HP, Skill", secondary: "Defense, Attribute" },
    ],
    items: [
      item("r1", "Arcane Double-Core Ring", "Other 1 / Red 2", "na", "Drops from most Digimon", false),
      item("r2", "Arcane Tri-core Ring", "Other 2 / Red 3", "na", "Drops from most Digimon", false),
      item("r3", "Arcane Quad-core Ring", "3", "na", "Etemon / SkullGreymon raid (Server Continent Desert)", false),
      item("r4", "Worn Desert Sand Ring", "4", "need", "100 Shiny Desert Coins at Wizardmon", true),
      item("r5", "Shiny High-powered Quad-core Ring", "4", "need", "MadLeomon Armed Mode, Etemon / SkullGreymon raid", true),
      item("r6", "Sealed Xuanwumon Ring", "4", "need", "MegaSeadramon raid box", true),
      item("r7", "Xuanwumon Sealed Shiny Ring", "4", "max", "Xuanwumon raid box", true),
      item("r8", "Ring of Sealed Zhuqiaomon", "4", "need", "Birdramon raid box", true),
      item("r9", "Flame Ring of Sealed Zhuqiaomon", "4", "max", "Zhuqiaomon raid box", true),
      item("r10", "Ring of Sealed Baihumon", "4", "need", "Sinduramon or Blossomon raid box", true),
      item("r11", "Aural Ring of Sealed Baihumon", "4", "max", "Blossomon or Baihumon raid box", true),
      item("r12", "Qinglongmon's Sealed Ring", "4", "need", "Antylamon raid box", true),
      item("r13", "Qinglongmon's Sealed Radiant Ring", "4", "max", "Qinglongmon raid box", true),
      item("r14", "Boundless Advanced Ring", "4", "max", "Digitamamon Item Make (Arena vouchers)", true),
      item("r15", "Miracle Ring [Level 10]", "4", "need", "Miracle Accessory ticket at Magnamon", true),
      item("r16", "Miracle Ring (Special)", "5", "need", "Lv.10 Miracle Ring + Shiny Quad-core at Magnamon", true),
      item("r17", "Fanglongmon's Ancient Ring [Lv.1–10]", "4", "need", "Fanglongmon raid / Digitamamon Item Make", true),
      item("r18", "Sealed Ring of Four Holy Beasts [Lv.1–5]", "4", "need", "Item Make (Scar of Water Crystal Hard mats)", true),
      item("r19", "Sealed Radiant Ring of Four Holy Beasts [Lv.1–5]", "4", "need", "Item Make (Descending Thunder God Hard mats)", true),
      item("r20", "Shining Arena Ring", "5", "need", "Digimon Arena Hard coins", true),
    ],
  },
  {
    slug: "necklaces",
    title: "Necklaces",
    blurb:
      "Necklaces are the Attack Speed and Critical Damage slot. They also roll Attack, Attribute, HP, DS, Defense, and Skill.",
    roles: [
      { role: "SK", primary: "Attack, Attribute", secondary: "Skill, Max HP" },
      { role: "AA", primary: "Attack Speed, Critical Damage", secondary: "Attack, Attribute" },
      { role: "TA", primary: "Max HP, Defense", secondary: "Attack Speed" },
      { role: "SUP", primary: "Max HP, Defense", secondary: "Attack Speed, Attribute" },
    ],
    items: [
      item("n1", "Arcane Tri-core Necklace", "Other 2 / Red 3", "na", "Gazimon in Datamon Maze", false),
      item("n2", "Arcane Quad-core Necklace", "3", "na", "Etemon raid in Datamon Maze", false),
      item("n3", "Sealed Necklace of Datamon", "3", "na", "Breaking the Datamon Maze (Hero) quest", false),
      item("n4", "Shiny High-Powered Quad-Core Necklace", "4", "need", "Etemon raid, Datamon Maze Hero", true),
      item("n5", "Sealed Xuanwumon Necklace", "4", "need", "MarineDevimon raid box", true),
      item("n6", "Xuanwumon Sealed Shiny Necklace", "4", "max", "Xuanwumon raid box", true),
      item("n7", "Zhuqiaomon Sealed Necklace", "4", "need", "Garudamon raid box", true),
      item("n8", "Flame Necklace of Sealed Zhuqiaomon", "4", "max", "Zhuqiaomon raid box", true),
      item("n9", "Necklace of Sealed Baihumon", "4", "need", "Blossomon raid box", true),
      item("n10", "Aural Necklace of Sealed Baihumon", "4", "max", "Blossomon or Baihumon raid box", true),
      item("n11", "Qinglongmon's Sealed Necklace", "4", "need", "Mihiramon raid box", true),
      item("n12", "Qinglongmon's Sealed Radiant Necklace", "4", "max", "Qinglongmon raid box", true),
      item("n13", "Boundless Advanced Necklace", "4", "max", "Digitamamon Item Make (Arena vouchers)", true),
      item("n14", "Miracle Necklace [Level 10]", "4", "need", "Miracle Accessory ticket at Magnamon", true),
      item("n15", "Miracle Necklace (Special)", "5", "need", "Lv.10 Miracle Necklace + a max-roll necklace at Magnamon", true),
      item("n16", "Fanglongmon's Ancient Necklace [Lv.1–10]", "4", "need", "Fanglongmon raid / Digitamamon Item Make", true),
      item("n17", "Sealed Necklace of Four Holy Beasts [Lv.1–5]", "4", "need", "Item Make (Uprising Flame Hard mats)", true),
      item("n18", "Sealed Radiant Necklace of Four Holy Beasts [Lv.1–5]", "4", "need", "Item Make (Descending Thunder God Hard mats)", true),
    ],
  },
  {
    slug: "earrings",
    title: "Earrings",
    blurb:
      "Earrings carry Hit Rate, Critical Damage, Block, and Evasion. Skill Attackers still want Skill and Attribute here.",
    roles: [
      { role: "SK", primary: "Skill, Attribute", secondary: "Critical Damage, Hit Rate" },
      { role: "AA", primary: "Critical Damage, Hit Rate", secondary: "Attribute, Max HP" },
      { role: "TA", primary: "Max HP, Defense, Block", secondary: "Evasion" },
      { role: "SUP", primary: "Max HP, Hit Rate", secondary: "Skill, Defense" },
    ],
    items: [
      item("e1", "Growth Accessory (Earrings)", "3", "na", "Jumping / event; stones cannot be used", false),
      item("e2", "Earring of Sealed Zhuqiaomon", "3", "need", "Phoenixmon raid box", true),
      item("e3", "Flame Earring of Sealed Zhuqiaomon", "3", "need", "Zhuqiaomon raid box", true),
      item("e4", "Earring of Sealed Baihumon", "3", "need", "Blossomon or Baihumon raid box", true),
      item("e5", "Aural Earring of Sealed Baihumon", "3", "max", "Baihumon raid box", true),
      item("e6", "Qinglongmon's Sealed Earring", "4", "need", "Majiramon raid box", true),
      item("e7", "Qinglongmon's Sealed Radiant Earring", "4", "max", "Qinglongmon raid box", true),
      item("e8", "Shiny High-Powered Quad-Core Earrings", "4", "need", "Digitamamon server reward", true),
      item("e9", "Boundless Advanced Earrings", "4", "max", "Digitamamon Item Make (Arena vouchers)", true),
      item("e10", "Miracle Earrings [Level 10]", "4", "need", "Miracle Accessory ticket at Magnamon", true),
      item("e11", "Miracle Earring [Special]", "5", "need", "Lv.10 Miracle Earrings + Qinglongmon Radiant at Magnamon", true),
      item("e12", "Fanglongmon's Ancient Earring [Lv.1–10]", "4", "need", "Fanglongmon raid / Digitamamon Item Make", true),
      item("e13", "Sealed Earrings of Four Holy Beasts [Lv.1–5]", "4", "need", "Item Make (Trace of Black Steel Hard mats)", true),
      item("e14", "Sealed Radiant Earrings of Four Holy Beasts [Lv.1–5]", "4", "need", "Item Make (Descending Thunder God Hard mats)", true),
    ],
  },
  {
    slug: "bracelets",
    title: "Bracelets",
    blurb:
      "Bracelets stack Hit Rate and Critical Damage. Attack only appears on Miracle, Royal X-Knight, and Zero Unit lines.",
    roles: [
      { role: "SK", primary: "Attack, Skill", secondary: "Critical Damage, Hit Rate" },
      { role: "AA", primary: "Attack, Critical Damage, Hit Rate", secondary: "Skill" },
      { role: "TA", primary: "Max HP, Defense, Evasion", secondary: "Hit Rate" },
      { role: "SUP", primary: "Max HP, Skill, Hit Rate", secondary: "Defense" },
    ],
    items: [
      item("b1", "Shabby Bracelet of Ruins", "1", "need", "Item Make (Ancient Ruins of Secret)", false),
      item("b2", "Shiny Bracelet of Ruins", "2", "need", "Item Make (Ancient Ruins of Secret)", false),
      item("b3", "Fancy Bracelet of Ancient Breath", "3", "need", "Item Make (Ancient Ruins of Secret)", true),
      item("b4", "Crude Rusty Bracelet", "1", "need", "Gallantmon quest, Versandi Terminal", false),
      item("b5", "Knight's Bracelet", "1", "need", "Digitamamon Item Make", false),
      item("b6", "Radiant Knight's Bracelet", "2", "need", "Digitamamon Item Make", false),
      item("b7", "Royal : Knight's Bracelet", "3", "need", "Digitamamon Item Make", true),
      item("b8", "Royal : Radiant Knight's Bracelet", "4", "need", "Digitamamon Item Make", true),
      item("b9", "Royal : X-Knight's Bracelet", "5", "need", "Digitamamon Item Make", true),
      item("b10", "Miracle Bracelet [Level 10]", "5", "need", "Miracle Accessory ticket at Magnamon", true),
      item("b11", "Miracle Bracelet [Special]", "5", "need", "Lv.10 Miracle Bracelet + Royal X-Knight at Magnamon", true),
      item("b12", "Zero Unit Bracelet", "5", "max", "Event Data summon", true),
    ],
  },
];
